### PR TITLE
Loading spinner

### PR DESCRIPTION
**Pull request by memetcircus**
Insert Spinner to view, if not succeed in loading it shows "Can not load" warning label, plus Swift 3.0 updates

### CODE REVIEW

**Comment by kwstasna** [comment]
Is this library not supported anymore from the creator ? @gilesvangruisen

**Comment by Mohammed-Eliass** [comment]
if you added the loading spinner, could you please share with us how to use it ?

**Comment by memetcircus** [comment]
@Mohammed-Eliass tried to share and waited for the approval of the commit but the creator did not response for a long time so decided to cancel the pull request. Sorry

**Comment by gilesvangruisen** [comment]
Really sorry for the delay here, folks! I have not been actively developing in Swift these days and as such have unfortunately let this library slip a bit.

That said, I'm not sure I'm on board adding a spinner here anyways, and I think I'd prefer to leave that functionality to the developer, aka the consumer of this library.

You can use the `YouTubePlayerDelegate` delegate methods to achieve this functionality of showing/hiding a loading indicator. Hope this helps. Thanks!

**Comment by chnouman** [comment]
works for me thanks.

**Pull request closed without merging**
