### PR TITLE
Cocoapods Integration

### PR DESCRIPTION
**Pull request by coreyauger**
Created a podspec for easy integration.

### CODE REVIEW

**Comment by gilesvangruisen** [comment]
This is slick. Thanks so much!

Only thing is that it looks like this both upgrades for swift 1.2 (something I've been meaning to get to) and add podspec. I'd like to be able to maintain a release with swif 1.1 support that includes a podspec, and then update master to 1.2.

Any way you could split this up into a podspec PR that we I get merged and release ASAP and then a separate 1.2 PR to merge and release afterwards?

Thanks again!

**Comment by gilesvangruisen** [comment]
This is slick. Thanks so much!

Only thing is that it looks like this both upgrades for swift 1.2 (something I've been meaning to get to) and add podspec. I'd like to be able to maintain a release with swif 1.1 support that includes a podspec, and then update master to 1.2.

Any way you could split this up into a podspec PR that we I get merged and release ASAP and then a separate 1.2 PR to merge and release afterwards?

Thanks again!

**Comment by coreyauger** [comment]
Yes.  I will get you a separate podspec.  You will have to change some of the values before it will use your branch.  There will need to be a release tag that you use as well as pointing it to your master branch.  I can send you some notes on what values you will want to change.  Thanks :)

**Comment by gilesvangruisen** [comment]
Awesome, that's still a huge help. Cheers! :)

**Comment by gilesvangruisen** [comment]
Closing for lack of activity… have a separate PR dedicated to Cocoapods support for the current library. #16

**Pull request closed without merging**
