### PR TITLE
Changes YouTubePlayerDelegate to a weak reference 

### PR DESCRIPTION
**Pull request by owenworley**
as delegates should not be strong

### CODE REVIEW

**Comment by gilesvangruisen** [comment]
Hi @owenworley! Thanks for using this library.

I like the goal of this PR, but I believe it has some unfortunate and quite restricting consequences for what is a fairly marginal improvement in safety.

Weak references are great for avoiding strong reference cycles; however this only becomes an issue in a two-way relationship (`a` and `b` both have a strong reference to each other). In this case, the relationship is one-way, with `YouTubePlayerView` storing a reference to some instance of a `YouTubePlayerDelegate`-conforming type. As such, a strong reference cycle is unlikely, if not guaranteed not to happen.

The consequences I mentioned come from constraining `YouTubePlayerDelegate` to classes. I personally love using structs as delegates because it separates that logic in a clear and reusable way, and they're not reference objects so the risk of creating a strong reference cycle is greatly reduced.

If the end goal is safety and avoiding strong reference cycles, then I think the optimal solution is to create a dedicated structure responsible for handling `YouTubePlayerDelegate` methods, or to continue using the library as-is.

I'm going to close this for now but please do let me know if I'm missing anything. Thanks, again!

**Comment by owenworley** [comment]
Hi @gilesvangruisen 

My first use of SwiftYouTubePlayer resulted in the strong retain cycle described.

My use case is:
A music player view controller which loads Youtube in a container view. PlayerViewController requires a reference to YouTube so that it can invoke player commands using the Play/Pause API.
PlayerViewController is also the delegate to the youtube view, as it needs to handle responses to playback pause/play/buffering events.

This seems a common use case, and results in a strong retain cycle, apart from storing the delegate as weak, I don't see a way to resolve this retain cycle.

What are your thoughts for another solution?

**Comment by gilesvangruisen** [comment]
@owenworley I ended up running into this and I've changed my opinion on the matter. I think this is a worthy update, so I've gone and merged it. Thanks :D

**Comment by owenworley** [comment]
:)

**Pull request merged**
