### PR TITLE
Use WKWebView + fix various issues

### LINKED ISSUE #164: UIWebView Deprecated!
Transition from UIWebView to WKWebView (iOS) possible? Swift 5 and IOS 12 will most likely not include UIWebView anymore.

### LINKED ISSUE #169: Pod update 0.5
Not able to update to version 0.5

### LINKED ISSUE #171: Example app broken
The current example app builds but crashes with an "image not found" message. I noticed all the IBOutlets were broken so I reconnected them, but that did not stop the crash. Would love to check out your solution, but can't get example app to launch.

### LINKED ISSUE #172: App crashing in iOS 12
I have started using this library in iOS 12 and when I drag video player around the screen then my app is getting crashed. But it is working fine in iOS 11 and 10. Any fix for iOS 12?

### PR DESCRIPTION
**Pull request by weakfl**
Refactor to WKWebView and fix various issues:

- fix #172
- fix #171
- fix #164 

@gilesvangruisen:
I've only done minimal testing as my main focus was to fix the iOS 12 issue, so you might want to do some additional testing.
If you merge this, could you please also make a new release and push it to cocoapods? Doing so should also resolve #169

### CODE REVIEW

**Comment by kanjihasnain** [comment]
@weakfl I need this fix project please merge it in master branch thanks.

**Comment by weakfl** [comment]
@kanjihasnain I'm not the owner of the project, so I can't merge this PR.

If you need a workaround, use the branch from my fork until this gets merged:
```
pod 'YouTubePlayer', :git => 'https://github.com/weakfl/Swift-YouTube-Player.git', :branch => 'use-wkwebview' # replace with original pod after the pull request got merged
```

**Comment by dkk** [comment]
> @kanjihasnain I'm not the owner of the project, so I can't merge this PR.
> 
> If you need a workaround, use the branch from my fork until this gets merged:
> 
> ```
> pod 'YouTubePlayer', :git => 'https://github.com/weakfl/Swift-YouTube-Player.git', :branch => 'use-wkwebview' # replace with original pod after the pull request got merged
> ```

I don't see a player using that branch. My code works with the master branch

**Comment by gilesvangruisen** [comment]
Hey y’all, really sorry about the delay!

Late last night I pushed the updated, Swift 5 compatible pod. You can now upgrade to 0.6.0 via Cocoapods.

There other issue is the deprecation issue around `UIWebView`. There are other open issues and PRs which I will take a look at today and try to push an update to support `WKWebView`.

 I’ll close this when that’s updated, but for now, the primary issue of Swift 5 Pod availability should be resolved.

Please let me know if you have any questions. Thank you all for filing the issue and chiming in, and obviously thank you for using this library!

**Comment by gilesvangruisen** [comment]
Merged via fb0f7029337afba541784568419203361ffa0f7f 43b0ba6b195a77a8de7cb456488b1fc70d4c3a66 ea6684c18693480bfc7688914fcf9737b2235e83 6256deb6d323f70a5037da9afdd1349725d64045

Thank you @weakfl and sorry again everyone! Unfortunately this does cause some breaking changes, so I need to make some readme updates before cutting a new release/pushing to Cocoapods. Bear with me! 🙏

**Pull request closed without merging**
