### PR TITLE
FIX Updated for Xcode 10 and Swift 4.2

### PR DESCRIPTION
**Pull request by schumy**

### CODE REVIEW

**Comment by huyduc** [comment]
Can we merge this please?

**Comment by emanueluayza** [comment]
It would be great if we can merge this :)

**Comment by weakfl** [comment]
Merge please, thanks.

**Comment by Mehdzor** [comment]
@gilesvangruisen hello?

**Comment by weakfl** [comment]
@gilesvangruisen Thanks for merging, now we need a new release please 😉

**Comment by weakfl** [comment]
@gilesvangruisen Thanks, but the new version is not available on cocoapods. I guess because linting fails. I've created a PR to fix the podspec: #168

**NOTE:** You'll have to move the tag `v0.5.0` to the new commit or make a new release...

**Pull request merged**
