### PR TITLE
Optional protocol functions

### PR DESCRIPTION
**Pull request by thomasvalera**
Made all YouTubePlayerDelegate functions optional while staying 100% Swift.

### CODE REVIEW

**Comment by gilesvangruisen** [comment]
@thomasvalera sorry for the delay- this is a fantastic change. Thanks so much!

Do you mind just changing the preceding comment to something simpler like: `// Make delegate methods optional by providing default implementations`

Also if you don't mind, there's still a bit in the README about these methods being all-or-none, which is no longer the case. Do you mind removing that last paragraph and maybe clarifying where the methods are listed above to mention they are all optional?

Thanks again! :)

**Comment by gilesvangruisen** [comment]
@thomasvalera any update here?

**Comment by thomasvalera** [comment]
@gilesvangruisen Yes, I will update it this weekend!

**Comment by gilesvangruisen** [comment]
@thomasvalera awesome, thanks

**Comment by gilesvangruisen** [comment]
@thomasvalera bump

Any update here?

**Comment by thomasvalera** [comment]
@gilesvangruisen All done!

**Comment by gilesvangruisen** [comment]
@thomasvalera excellent, thanks so much!

**Pull request merged**
